project:
  type: website
  output-dir: docs
  
website:
  title: "ASEAN stats and R"
  navbar:
    left:
      - index.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/jimstankovich/jtr_tutorial
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "Last updated 2 July 2024"

format:
  html:
    theme: default
    toc: true

editor: source

