project:
  type: website
  output-dir: docs
  
website:
  title: "Notes in Bang Pho"
  navbar:
    left:
      - index.qmd
      - bangkok.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/jimstankovich/notes
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "Last updated 4 July 2024"

format:
  html:
    theme: default
    toc: true

editor: source

